/*
  CMPUT201W20 Final Question 4 TEST DRIVER for ziwei11
  
  DO NOT CHANGE THIS FILE!
  
  DO NOT EDIT THIS FILE!
  
  DO NOT MODIFY THIS FILE!
  
   VERSION: 0.9.0
*/
#define LOGFILE "question4_test.log"

// Link question4 with purefloat_ops.c not myfloat_ops.c
// The tests are the same as the test for question2.
#include "question2_test.c" 
