/*
  CMPUT201W20 Final Question 3 TEST DRIVER for ziwei11
  
  DO NOT CHANGE THIS FILE!
  
  DO NOT EDIT THIS FILE!
  
  DO NOT MODIFY THIS FILE!
  
   VERSION: 0.9.0
*/
#include "myfloat_conv.h"
#include "test.h"
#include <limits.h>

#ifndef LOGFILE
#define LOGFILE "question3_test.log"
#endif

int main() {
    setup("question3_test.log");
    
    char * buf;

    MyFloat pzero = str_to_myfloat("0");
    ASSERT_INT_EQUAL(myfloat_negative(pzero), 0);
    ASSERT_INT_EQUAL(myfloat_exponent(pzero), INT_MIN);
    ASSERT_INT_EQUAL(myfloat_mantissa(pzero), 0);
    ASSERT_BYTES_EQUAL(pzero, 0x00000000U);
    buf = myfloat_to_str(pzero);
    ASSERT_STR_EQUAL(buf, "0");
    free(buf);
    
    MyFloat nzero = str_to_myfloat("-0");
    ASSERT_INT_EQUAL(myfloat_negative(nzero), 1);
    ASSERT_INT_EQUAL(myfloat_exponent(nzero), INT_MIN);
    ASSERT_INT_EQUAL(myfloat_mantissa(nzero), 0);
    ASSERT_BYTES_EQUAL(nzero, 0x80000000U);
    buf = myfloat_to_str(nzero);
    ASSERT_STR_EQUAL(buf, "-0");
    free(buf);
    
    MyFloat pone = str_to_myfloat("1");
    ASSERT_INT_EQUAL(myfloat_negative(pone), 0);
    ASSERT_INT_EQUAL(myfloat_exponent(pone), 0);
    ASSERT_INT_EQUAL(myfloat_mantissa(pone), 1 << MANTISSA_BITS);
    ASSERT_BYTES_EQUAL(pone, 0x3fe00000U);
    buf = myfloat_to_str(pone);
    ASSERT_STR_EQUAL(buf, "1.00e+00");
    free(buf);
    
    MyFloat n1 = str_to_myfloat("-1");
    myfloat_set_negative(&n1, 1);
    ASSERT_INT_EQUAL(myfloat_negative(n1), 1);
    ASSERT_INT_EQUAL(myfloat_exponent(n1), 0);
    ASSERT_INT_EQUAL(myfloat_mantissa(n1), 1 << MANTISSA_BITS);
    ASSERT_BYTES_EQUAL(n1, 0xbfe00000U);
    buf = myfloat_to_str(n1);
    ASSERT_STR_EQUAL(buf, "-1.00e+00");
    free(buf);
    
    MyFloat buck_quarter = str_to_myfloat("1.25");
    ASSERT_INT_EQUAL(myfloat_negative(buck_quarter), 0);
    ASSERT_INT_EQUAL(myfloat_exponent(buck_quarter), 0);
    ASSERT_INT_CLOSE(myfloat_mantissa(buck_quarter), 5 << (MANTISSA_BITS-2));
    buf = myfloat_to_str(buck_quarter);
    ASSERT_STR_EQUAL(buf, "1.25e+00");
    free(buf);
    
    MyFloat quarter = str_to_myfloat("2.5e-1");
    ASSERT_INT_EQUAL(myfloat_negative(quarter), 0);
    ASSERT_INT_EQUAL(myfloat_exponent(quarter), -2);
    ASSERT_INT_EQUAL(myfloat_mantissa(quarter), 1 << MANTISSA_BITS);
    buf = myfloat_to_str(quarter);
    ASSERT_STR_EQUAL(buf, "2.50e-01");
    free(buf);

    MyFloat p64 = str_to_myfloat("6.4e1");
    ASSERT_INT_EQUAL(myfloat_negative(p64), 0);
    ASSERT_INT_EQUAL(myfloat_exponent(p64), 6);
    ASSERT_INT_EQUAL(myfloat_mantissa(p64), 1 << MANTISSA_BITS);
    buf = myfloat_to_str(p64);
    ASSERT_STR_EQUAL(buf, "6.40e+01");
    free(buf);

    MyFloat p177 = str_to_myfloat("17.7e1");
    ASSERT_INT_EQUAL(myfloat_negative(p177), 0);
    ASSERT_INT_EQUAL(myfloat_exponent(p177), 7);
    ASSERT_INT_EQUAL(myfloat_mantissa(p177), 177 << (MANTISSA_BITS-7));
    buf = myfloat_to_str(p177);
    ASSERT_STR_EQUAL(buf, "1.77e+02");
    free(buf);
    
    MyFloat oneohone = str_to_myfloat("0.02197265625");
    ASSERT_INT_EQUAL(myfloat_negative(oneohone), 0);
    ASSERT_INT_EQUAL(myfloat_exponent(oneohone), -6);
    ASSERT_INT_EQUAL(myfloat_mantissa(oneohone), 45 << (MANTISSA_BITS-5));
    buf = myfloat_to_str(oneohone);
    ASSERT_STR_EQUAL(buf, "2.20e-02");
    free(buf);

    MyFloat n111;
    myfloat_set_negative(&n111, 1);
    myfloat_set_mantissa(&n111, 111 << (MANTISSA_BITS-6));
    myfloat_set_exponent(&n111, 6);
    buf = myfloat_to_str(n111);
    ASSERT_STR_EQUAL(buf, "-1.11e+02");
    free(buf);

    {
        MyFloat r64 = str_to_myfloat("-1.562500e-02");
        ASSERT_INT_EQUAL(myfloat_negative(r64), 1U);
        if (myfloat_exponent(r64) == -6) {
            ASSERT_INT_EQUAL(myfloat_exponent(r64), -6U);
            ASSERT_INT_CLOSE(myfloat_mantissa(r64), 2097152U);
            ASSERT_BYTES_CLOSE(r64, 0xbf200000U);
        } else {
            ASSERT_INT_EQUAL(myfloat_exponent(r64), -7U);
            ASSERT_INT_CLOSE(myfloat_mantissa(r64), 4194303U);
            ASSERT_BYTES_CLOSE(r64, 0xbf200000U);
        }
    }
    {
        MyFloat r64 = myfloat_zero();
        myfloat_set_negative(&r64, 1U);
        myfloat_set_exponent(&r64, -6U);
        myfloat_set_mantissa(&r64, 2097152U);
        buf = myfloat_to_str(r64);
        ASSERT_STR_EQUAL(buf, "-1.56e-02");
        free(buf);
    }
    
    {
        MyFloat r32 = str_to_myfloat("3.125000e-02");
        ASSERT_INT_EQUAL(myfloat_negative(r32), 0U);
        if (myfloat_exponent(r32) == -5) {
            ASSERT_INT_EQUAL(myfloat_exponent(r32), -5U);
            ASSERT_INT_CLOSE(myfloat_mantissa(r32), 2097152U);
            ASSERT_BYTES_CLOSE(r32, 0x3f400000U);
        } else {
            ASSERT_INT_EQUAL(myfloat_exponent(r32), -6U);
            ASSERT_INT_CLOSE(myfloat_mantissa(r32), 4194303U);
            ASSERT_BYTES_CLOSE(r32, 0x3f400000U);
        }
    }
    {
        MyFloat r32 = myfloat_zero();
        myfloat_set_negative(&r32, 0U);
        myfloat_set_exponent(&r32, -5U);
        myfloat_set_mantissa(&r32, 2097152U);
        buf = myfloat_to_str(r32);
        ASSERT_STR_EQUAL(buf, "3.12e-02");
        free(buf);
    }
    
    {
        MyFloat r16 = str_to_myfloat("-6.250000e-02");
        ASSERT_INT_EQUAL(myfloat_negative(r16), 1U);
        if (myfloat_exponent(r16) == -4) {
            ASSERT_INT_EQUAL(myfloat_exponent(r16), -4U);
            ASSERT_INT_CLOSE(myfloat_mantissa(r16), 2097152U);
            ASSERT_BYTES_CLOSE(r16, 0xbf600000U);
        } else {
            ASSERT_INT_EQUAL(myfloat_exponent(r16), -5U);
            ASSERT_INT_CLOSE(myfloat_mantissa(r16), 4194303U);
            ASSERT_BYTES_CLOSE(r16, 0xbf600000U);
        }
    }
    {
        MyFloat r16 = myfloat_zero();
        myfloat_set_negative(&r16, 1U);
        myfloat_set_exponent(&r16, -4U);
        myfloat_set_mantissa(&r16, 2097152U);
        buf = myfloat_to_str(r16);
        ASSERT_STR_EQUAL(buf, "-6.25e-02");
        free(buf);
    }
    
    {
        MyFloat r8 = str_to_myfloat("1.250000e-01");
        ASSERT_INT_EQUAL(myfloat_negative(r8), 0U);
        if (myfloat_exponent(r8) == -3) {
            ASSERT_INT_EQUAL(myfloat_exponent(r8), -3U);
            ASSERT_INT_CLOSE(myfloat_mantissa(r8), 2097152U);
            ASSERT_BYTES_CLOSE(r8, 0x3f800000U);
        } else {
            ASSERT_INT_EQUAL(myfloat_exponent(r8), -4U);
            ASSERT_INT_CLOSE(myfloat_mantissa(r8), 4194303U);
            ASSERT_BYTES_CLOSE(r8, 0x3f800000U);
        }
    }
    {
        MyFloat r8 = myfloat_zero();
        myfloat_set_negative(&r8, 0U);
        myfloat_set_exponent(&r8, -3U);
        myfloat_set_mantissa(&r8, 2097152U);
        buf = myfloat_to_str(r8);
        ASSERT_STR_EQUAL(buf, "1.25e-01");
        free(buf);
    }
    
    {
        MyFloat r4 = str_to_myfloat("-2.500000e-01");
        ASSERT_INT_EQUAL(myfloat_negative(r4), 1U);
        if (myfloat_exponent(r4) == -2) {
            ASSERT_INT_EQUAL(myfloat_exponent(r4), -2U);
            ASSERT_INT_CLOSE(myfloat_mantissa(r4), 2097152U);
            ASSERT_BYTES_CLOSE(r4, 0xbfa00000U);
        } else {
            ASSERT_INT_EQUAL(myfloat_exponent(r4), -3U);
            ASSERT_INT_CLOSE(myfloat_mantissa(r4), 4194303U);
            ASSERT_BYTES_CLOSE(r4, 0xbfa00000U);
        }
    }
    {
        MyFloat r4 = myfloat_zero();
        myfloat_set_negative(&r4, 1U);
        myfloat_set_exponent(&r4, -2U);
        myfloat_set_mantissa(&r4, 2097152U);
        buf = myfloat_to_str(r4);
        ASSERT_STR_EQUAL(buf, "-2.50e-01");
        free(buf);
    }
    
    {
        MyFloat r2 = str_to_myfloat("5.000000e-01");
        ASSERT_INT_EQUAL(myfloat_negative(r2), 0U);
        if (myfloat_exponent(r2) == -1) {
            ASSERT_INT_EQUAL(myfloat_exponent(r2), -1U);
            ASSERT_INT_CLOSE(myfloat_mantissa(r2), 2097152U);
            ASSERT_BYTES_CLOSE(r2, 0x3fc00000U);
        } else {
            ASSERT_INT_EQUAL(myfloat_exponent(r2), -2U);
            ASSERT_INT_CLOSE(myfloat_mantissa(r2), 4194303U);
            ASSERT_BYTES_CLOSE(r2, 0x3fc00000U);
        }
    }
    {
        MyFloat r2 = myfloat_zero();
        myfloat_set_negative(&r2, 0U);
        myfloat_set_exponent(&r2, -1U);
        myfloat_set_mantissa(&r2, 2097152U);
        buf = myfloat_to_str(r2);
        ASSERT_STR_EQUAL(buf, "5.00e-01");
        free(buf);
    }
    
    {
        MyFloat p2 = str_to_myfloat("2.000000e+00");
        ASSERT_INT_EQUAL(myfloat_negative(p2), 0U);
        if (myfloat_exponent(p2) == 1) {
            ASSERT_INT_EQUAL(myfloat_exponent(p2), 1U);
            ASSERT_INT_CLOSE(myfloat_mantissa(p2), 2097152U);
            ASSERT_BYTES_CLOSE(p2, 0x40000000U);
        } else {
            ASSERT_INT_EQUAL(myfloat_exponent(p2), 0U);
            ASSERT_INT_CLOSE(myfloat_mantissa(p2), 4194303U);
            ASSERT_BYTES_CLOSE(p2, 0x40000000U);
        }
    }
    {
        MyFloat p2 = myfloat_zero();
        myfloat_set_negative(&p2, 0U);
        myfloat_set_exponent(&p2, 1U);
        myfloat_set_mantissa(&p2, 2097152U);
        buf = myfloat_to_str(p2);
        ASSERT_STR_EQUAL(buf, "2.00e+00");
        free(buf);
    }
    
    {
        MyFloat p4 = str_to_myfloat("4.000000e+00");
        ASSERT_INT_EQUAL(myfloat_negative(p4), 0U);
        if (myfloat_exponent(p4) == 2) {
            ASSERT_INT_EQUAL(myfloat_exponent(p4), 2U);
            ASSERT_INT_CLOSE(myfloat_mantissa(p4), 2097152U);
            ASSERT_BYTES_CLOSE(p4, 0x40200000U);
        } else {
            ASSERT_INT_EQUAL(myfloat_exponent(p4), 1U);
            ASSERT_INT_CLOSE(myfloat_mantissa(p4), 4194303U);
            ASSERT_BYTES_CLOSE(p4, 0x40200000U);
        }
    }
    {
        MyFloat p4 = myfloat_zero();
        myfloat_set_negative(&p4, 0U);
        myfloat_set_exponent(&p4, 2U);
        myfloat_set_mantissa(&p4, 2097152U);
        buf = myfloat_to_str(p4);
        ASSERT_STR_EQUAL(buf, "4.00e+00");
        free(buf);
    }
    
    {
        MyFloat n8 = str_to_myfloat("-8.000000e+00");
        ASSERT_INT_EQUAL(myfloat_negative(n8), 1U);
        if (myfloat_exponent(n8) == 3) {
            ASSERT_INT_EQUAL(myfloat_exponent(n8), 3U);
            ASSERT_INT_CLOSE(myfloat_mantissa(n8), 2097152U);
            ASSERT_BYTES_CLOSE(n8, 0xc0400000U);
        } else {
            ASSERT_INT_EQUAL(myfloat_exponent(n8), 2U);
            ASSERT_INT_CLOSE(myfloat_mantissa(n8), 4194303U);
            ASSERT_BYTES_CLOSE(n8, 0xc0400000U);
        }
    }
    {
        MyFloat n8 = myfloat_zero();
        myfloat_set_negative(&n8, 1U);
        myfloat_set_exponent(&n8, 3U);
        myfloat_set_mantissa(&n8, 2097152U);
        buf = myfloat_to_str(n8);
        ASSERT_STR_EQUAL(buf, "-8.00e+00");
        free(buf);
    }
    
    {
        MyFloat p16 = str_to_myfloat("1.600000e+01");
        ASSERT_INT_EQUAL(myfloat_negative(p16), 0U);
        if (myfloat_exponent(p16) == 4) {
            ASSERT_INT_EQUAL(myfloat_exponent(p16), 4U);
            ASSERT_INT_CLOSE(myfloat_mantissa(p16), 2097152U);
            ASSERT_BYTES_CLOSE(p16, 0x40600000U);
        } else {
            ASSERT_INT_EQUAL(myfloat_exponent(p16), 3U);
            ASSERT_INT_CLOSE(myfloat_mantissa(p16), 4194303U);
            ASSERT_BYTES_CLOSE(p16, 0x40600000U);
        }
    }
    {
        MyFloat p16 = myfloat_zero();
        myfloat_set_negative(&p16, 0U);
        myfloat_set_exponent(&p16, 4U);
        myfloat_set_mantissa(&p16, 2097152U);
        buf = myfloat_to_str(p16);
        ASSERT_STR_EQUAL(buf, "1.60e+01");
        free(buf);
    }
    
    {
        MyFloat n32 = str_to_myfloat("-3.200000e+01");
        ASSERT_INT_EQUAL(myfloat_negative(n32), 1U);
        if (myfloat_exponent(n32) == 5) {
            ASSERT_INT_EQUAL(myfloat_exponent(n32), 5U);
            ASSERT_INT_CLOSE(myfloat_mantissa(n32), 2097152U);
            ASSERT_BYTES_CLOSE(n32, 0xc0800000U);
        } else {
            ASSERT_INT_EQUAL(myfloat_exponent(n32), 4U);
            ASSERT_INT_CLOSE(myfloat_mantissa(n32), 4194303U);
            ASSERT_BYTES_CLOSE(n32, 0xc0800000U);
        }
    }
    {
        MyFloat n32 = myfloat_zero();
        myfloat_set_negative(&n32, 1U);
        myfloat_set_exponent(&n32, 5U);
        myfloat_set_mantissa(&n32, 2097152U);
        buf = myfloat_to_str(n32);
        ASSERT_STR_EQUAL(buf, "-3.20e+01");
        free(buf);
    }
    
    {
        MyFloat pinf = str_to_myfloat("inf");
        ASSERT_INT_EQUAL(myfloat_negative(pinf), 0U);
        ASSERT_INT_EQUAL(myfloat_exponent(pinf), INT_MAX);
        ASSERT_INT_EQUAL(myfloat_mantissa(pinf), 0U);
        ASSERT_BYTES_EQUAL(pinf, 0x7fe00000U);
    }
    {
        MyFloat pinf = myfloat_zero();
        myfloat_set_negative(&pinf, 0U);
        myfloat_set_exponent(&pinf, 512U);
        myfloat_set_mantissa(&pinf, 0U);
        buf = myfloat_to_str(pinf);
        ASSERT_STR_EQUAL(buf, "inf");
        free(buf);
    }
    
    {
        MyFloat ninf = str_to_myfloat("-inf");
        ASSERT_INT_EQUAL(myfloat_negative(ninf), 1U);
        ASSERT_INT_EQUAL(myfloat_exponent(ninf), INT_MAX);
        ASSERT_INT_EQUAL(myfloat_mantissa(ninf), 0U);
        ASSERT_BYTES_EQUAL(ninf, 0xffe00000U);
    }
    {
        MyFloat ninf = myfloat_zero();
        myfloat_set_negative(&ninf, 1U);
        myfloat_set_exponent(&ninf, 512U);
        myfloat_set_mantissa(&ninf, 0U);
        buf = myfloat_to_str(ninf);
        ASSERT_STR_EQUAL(buf, "-inf");
        free(buf);
    }
    
    {
        MyFloat sqrt2 = str_to_myfloat("1.414214e+00");
        ASSERT_INT_EQUAL(myfloat_negative(sqrt2), 0U);
        ASSERT_INT_EQUAL(myfloat_exponent(sqrt2), 0U);
        ASSERT_INT_CLOSE(myfloat_mantissa(sqrt2), 2965821U);
        ASSERT_BYTES_CLOSE(sqrt2, 0x3fed413dU);
    }
    {
        MyFloat sqrt2 = myfloat_zero();
        myfloat_set_negative(&sqrt2, 0U);
        myfloat_set_exponent(&sqrt2, 0U);
        myfloat_set_mantissa(&sqrt2, 2965821U);
        buf = myfloat_to_str(sqrt2);
        ASSERT_STR_EQUAL(buf, "1.41e+00");
        free(buf);
    }
    
    {
        MyFloat pi = str_to_myfloat("3.141593e+00");
        ASSERT_INT_EQUAL(myfloat_negative(pi), 0U);
        ASSERT_INT_EQUAL(myfloat_exponent(pi), 1U);
        ASSERT_INT_CLOSE(myfloat_mantissa(pi), 3294199U);
        ASSERT_BYTES_CLOSE(pi, 0x401243f7U);
    }
    {
        MyFloat pi = myfloat_zero();
        myfloat_set_negative(&pi, 0U);
        myfloat_set_exponent(&pi, 1U);
        myfloat_set_mantissa(&pi, 3294199U);
        buf = myfloat_to_str(pi);
        ASSERT_STR_EQUAL(buf, "3.14e+00");
        free(buf);
    }
    
    {
        MyFloat tenth = str_to_myfloat("-1.000000e-01");
        ASSERT_INT_EQUAL(myfloat_negative(tenth), 1U);
        ASSERT_INT_EQUAL(myfloat_exponent(tenth), -4U);
        ASSERT_INT_CLOSE(myfloat_mantissa(tenth), 3355443U);
        ASSERT_BYTES_CLOSE(tenth, 0xbf733333U);
    }
    {
        MyFloat tenth = myfloat_zero();
        myfloat_set_negative(&tenth, 1U);
        myfloat_set_exponent(&tenth, -4U);
        myfloat_set_mantissa(&tenth, 3355443U);
        buf = myfloat_to_str(tenth);
        if (buf[0] == '9') {
            ASSERT_STR_EQUAL(buf, "-9.99e-02");
        } else {
            ASSERT_STR_EQUAL(buf, "-1.00e-01");
        }
        free(buf);
    }
    
    {
        MyFloat hundredth = str_to_myfloat("1.000000e-02");
        ASSERT_INT_EQUAL(myfloat_negative(hundredth), 0U);
        ASSERT_INT_EQUAL(myfloat_exponent(hundredth), -7U);
        ASSERT_INT_CLOSE(myfloat_mantissa(hundredth), 2684355U);
        ASSERT_BYTES_CLOSE(hundredth, 0x3f08f5c3U);
    }
    {
        MyFloat hundredth = myfloat_zero();
        myfloat_set_negative(&hundredth, 0U);
        myfloat_set_exponent(&hundredth, -7U);
        myfloat_set_mantissa(&hundredth, 2684355U);
        buf = myfloat_to_str(hundredth);
        if (buf[0] == '9') {
            ASSERT_STR_EQUAL(buf, "9.99e-03");
        } else {
            ASSERT_STR_EQUAL(buf, "1.00e-02");
        }
        free(buf);
    }
    
    {
        MyFloat n10 = str_to_myfloat("-1.000000e+01");
        ASSERT_INT_EQUAL(myfloat_negative(n10), 1U);
        ASSERT_INT_EQUAL(myfloat_exponent(n10), 3U);
        ASSERT_INT_CLOSE(myfloat_mantissa(n10), 2621440U);
        ASSERT_BYTES_CLOSE(n10, 0xc0480000U);
    }
    {
        MyFloat n10 = myfloat_zero();
        myfloat_set_negative(&n10, 1U);
        myfloat_set_exponent(&n10, 3U);
        myfloat_set_mantissa(&n10, 2621440U);
        buf = myfloat_to_str(n10);
        if (buf[0] == '9') {
            ASSERT_STR_EQUAL(buf, "-9.99e+00");
        } else {
            ASSERT_STR_EQUAL(buf, "-1.00e+01");
        }
        free(buf);
    }
    
    {
        MyFloat n100 = str_to_myfloat("1.000000e+02");
        ASSERT_INT_EQUAL(myfloat_negative(n100), 0U);
        ASSERT_INT_EQUAL(myfloat_exponent(n100), 6U);
        ASSERT_INT_CLOSE(myfloat_mantissa(n100), 3276800U);
        ASSERT_BYTES_CLOSE(n100, 0x40b20000U);
    }
    {
        MyFloat n100 = myfloat_zero();
        myfloat_set_negative(&n100, 0U);
        myfloat_set_exponent(&n100, 6U);
        myfloat_set_mantissa(&n100, 3276800U);
        buf = myfloat_to_str(n100);
        if (buf[0] == '9') {
            ASSERT_STR_EQUAL(buf, "9.99e+01");
        } else {
            ASSERT_STR_EQUAL(buf, "1.00e+02");
        }
        free(buf);
    }
    
    teardown(LOGFILE);
}
